# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-11 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trends',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='imginfo',
            name='trends_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.Trends', verbose_name='文章id'),
        ),
        migrations.AddField(
            model_name='commit',
            name='trends_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.Trends', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='commit',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='attitude',
            name='trends_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.Trends', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='attitude',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
