# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-12 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_auto_20200511_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imginfo',
            name='img',
            field=models.ImageField(storage=system.storage.ImageStorage(), upload_to='trends_image/%Y/%m/%d', verbose_name='图片'),
        ),
    ]
